- name: Update all packages
  hosts: Integration_Centreon:Production_Centreon
  gather_facts: false
  tasks:
# Nor the yum nor the dnf Ansible module can set timeout and minrate options, so I use the command module, see below
#    - name: Update all packages
#      dnf:
#        name: '*'
#        state: latest
#        lock_timeout: 60
    - name: Update all packages
      command:
        cmd: dnf -y --setopt=timeout=120 --setopt=minrate=100 update
        warn: false
