---
- name: Miscellaneous shit
  hosts: Integration_Centreon
  gather_facts: false
  tasks:
    - name: Ensure some files aren’t world-writable
      command:
        cmd: chmod 0600 /etc/dnf/dnf.conf /etc/yum.conf
        warn: false
    
