---
- name: Miscellaneous shit to do on pollers
  hosts: collecteurs_centreon
  tasks:
    - name: Manage starting of services
      shell:
        cmd: systemctl enable centreon centengine centreontrapd snmptrapd && systemctl start centreontrapd snmptrapd && systemctl restart centengine
