---
- name: Install Oracle packages
  hosts: collecteurs_centreon_int:central_centreon_int
  gather_facts: false
  tasks:
    - name: Set vars from encrypted file
      include_vars:
        file: vars.yml
      no_log: true
    - name: Download Oracle client RPM from Artifactory
      get_url:
        url: "http://art37etu2.hm.dm.ad:8082/artifactory/oraclient-rhel8/{{item}}"
        dest: /tmp
        mode: 0755
        username: "{{artifactory_user}}"
        password: "{{artifactory_password}}"
      with_items:
        - oracle-instantclient-basic-21.7.0.0.0-1.el8.x86_64.rpm
        - oracle-instantclient-devel-21.7.0.0.0-1.el8.x86_64.rpm
        - oracle-instantclient-sqlplus-21.7.0.0.0-1.el8.x86_64.rpm
    - name: Install the Oracle client
      dnf:
        name:
          - /tmp/oracle-instantclient-basic-21.7.0.0.0-1.el8.x86_64.rpm
          - /tmp/oracle-instantclient-devel-21.7.0.0.0-1.el8.x86_64.rpm
          - /tmp/oracle-instantclient-sqlplus-21.7.0.0.0-1.el8.x86_64.rpm
        state: present
        disable_gpg_check: true
    - name: Delete temporary files
      shell:
        cmd: rm -f /tmp/oracle-instantclient-*
