---
- name: Install some packages
  hosts: Integration_Centreon
  gather_facts: false
  tasks:
    - name: Install useful utilities
      yum:
        name: nano openldap-clients lsof traceroute yum-utils
        state: present
 
