---
- name: Install some packages on central server only
  hosts: centraux_centreon
  tasks:
    - name: Install the centreon-central package
      yum:
        name: centreon-central
        state: present
    - name: Install the policycoreutils-python-utils package
      yum:
        name: policycoreutils-python-utils
        state: present
