---
- name: Install some packages on poller (central being considered as a poller too)
  hosts: collecteurs_centreon_int:central_centreon_int
  gather_facts: false
  tasks:
    - name: Install the policycoreutils-python-utils package
      dnf:
        name: policycoreutils-python-utils
        state: present
    - name: Install the centreon-poller package
      dnf:
        name: centreon-poller
        state: present
    - name: Install the net-snmp-utils package
      dnf:
        name: net-snmp-utils
        state: present
    - name: Install the rsync package
      dnf:
        name: rsync
        state: present
    - name: Install some monitoring plugins and their dependencies
      dnf:
        name:
          - centreon-plugin-Applications-Protocol-Nrpe
          - centreon-plugin-Applications-Protocol-Tcp
          - centreon-plugin-Network-Firewalls-Checkpoint-Snmp
          - centreon-plugin-Applications-Protocol-X509
          - centreon-plugin-Operatingsystems-Aix-Snmp
          - centreon-plugin-Applications-Databases-Oracle
          - centreon-plugin-Applications-Databases-Postgresql
          - perl-DBD-Pg
          - centreon-plugin-Hardware-Storage-Hitachi-Hnas-Snmp
          - centreon-plugin-Hardware-Storage-Hitachi-Standard-Snmp
          - nagios-plugins-cluster
          - nagios-plugins-snmp
          - nagios-plugins-nrpe
          - perl-Nagios-Plugin
        state: present
    - name: Install miscellaneaous packages
      dnf:
        name: jq, gcc
        state: present
