---
- name: Install some packages
  hosts: Intégration Centreon
  tasks:
    - name: Install the nano editor
      yum:
        name: nano
        state: present
     - name: Install the LDAP clients
      yum:
        name: openldap-clients
        state: present
