---
- name: Install some packages on the database server only
  hosts: database_centreon
  gather_facts: false
  tasks:
    - name: Install the centreon-database package
      yum:
        name: centreon-database
        state: present
