---
- name: Install some packages on poller only
  hosts: collecteurs_centreon
  gather_facts: false
  tasks:
    - name: Install the policycoreutils-python-utils package
      yum:
        name: policycoreutils-python-utils
        state: present
    - name: Install the centreon-poller package
      yum:
        name: centreon-poller
        state: present
    - name: Install the net-snmp-utils package
      yum:
        name: net-snmp-utils
        state: present
    - name: Install the rsync package
      yum:
        name: rsync
        state: present
    - name: Install some monitoring plugins
      yum:
        name: centreon-plugin-Applications-Protocol-Nrpe, centreon-plugin-Applications-Protocol-Tcp
        state: present
