---
- name: Install some packages
  hosts: Integration_Centreon
  gather_facts: false
  tasks:
    - name: Install the nano editor
      yum:
        name: nano
        state: present
    - name: Install the LDAP clients
      yum:
        name: openldap-clients
        state: present
    - name: Install the lsof utility
      yum:
        name: lsof
        state: present
    - name: Install the traceroute utility
      yum:
        name: traceroute
        state: present
    - name: Install the needs-restarting utility
      yum:
        name: needs-restarting
        state: present
 
