---
- name: Install some packages on central server only
  hosts: central_centreon
  gather_facts: false
  tasks:
    - name: Install the centreon-central package
      yum:
        name: centreon-central
        state: present
    - name: Install the policycoreutils-python-utils package
      yum:
        name: policycoreutils-python-utils
        state: present
    - name: Install plugin packs repository
      command:
        cmd:  yum -y install https://yum.centreon.com/plugin-packs/2e83f5ff110c44a9cab8f8c7ebbe3c4f/22.04/el8/stable/noarch/RPMS/centreon-plugin-packs-release-22.04-3.el8.noarch.rpm
        warn: false
    - name: Install the rsync package
      yum:
        name: rsync
        state: present
     - name: Install miscellaneaous packages
       yum:
         name: jq, python2-pip
         state: present
