---
- name: Install some packages on poller (central being considered as a poller too)
  hosts: collecteurs_centreon:central_centreon
  gather_facts: false
  tasks:
    - name: Install the policycoreutils-python-utils package
      yum:
        name: policycoreutils-python-utils
        state: present
    - name: Install the centreon-poller package
      yum:
        name: centreon-poller
        state: present
    - name: Install the net-snmp-utils package
      yum:
        name: net-snmp-utils
        state: present
    - name: Install the rsync package
      yum:
        name: rsync
        state: present
    - name: Install some monitoring plugins and dependencies
      yum:
        name:
          - centreon-plugin-Applications-Protocol-Nrpe
          - centreon-plugin-Applications-Protocol-Tcp
          - centreon-plugin-Network-Firewalls-Checkpoint-Snmp
          - nagios-plugins-cluster
          - nagios-plugins-snmp
          - centreon-plugin-Applications-Protocol-X509
          - centreon-plugin-Operatingsystems-Aix-Snmp
          - centreon-plugin-Applications-Databases-Oracle
          - perl-Nagios-Plugin
          - centreon-plugin-Hardware-Storage-Hitachi-Hnas-Snmp
          - centreon-plugin-Hardware-Storage-Hitachi-Standard-Snmp
        state: present
    - name: Install miscellaneaous packages
      yum:
        name: jq
        state: present
