---
- name: Activate PHP 8
  hosts: central_centreon_int
  gather_facts: false
  tasks:
    - name: Reset module PHP
      command:
        cmd: dnf -y module reset php
        warn: false
    - name: Install PHP 8
      command:
        cmd: dnf -y module install php:remi-8.0
        warn: false
 
