---
- name: Activate PHP 8
  hosts: serveurs centraux centreon
  tasks:
    - name: Reset module PHP
      command:
        cmd: dnf module reset php
        warn: false
    - name: Install PHP 8
      command:
        cmd: dnf module install php:remi-8.0
        warn: false
 
