---
- name: Prerequisites
  hosts: Integration_Centreon
  gather_facts: false
  tasks:
    - name: Install DNF plugins
      shell:
        cmd: dnf install -y dnf-plugins-core
        warn: false
    - name: Install EPEL repository
      shell:
        cmd: dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        warn: false
    - name: Install REMI repository
      shell:
        cmd: dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        warn: false
      when: inventory_hostname in groups['central_centreon_int']
    - name: Enable CodeReady Builder repository
      shell:
        cmd: subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
        warn: false
      when: inventory_hostname in groups['central_centreon_int'] or inventory_hostname in groups['collecteurs_centreon_int']
    - name: Install Centreon repository
      shell:
        cmd: dnf install -y https://yum.centreon.com/standard/22.04/el8/stable/noarch/RPMS/centreon-release-22.04-3.el8.noarch.rpm
        warn: false
