---
- name: Install Python 2 + GCC + PIP + some Python libraries
  hosts: central_centreon_int
  gather_facts: false
  tasks:
    - name: Install Python 2 + GCC + PIP + some Python libraries
      dnf:
        name:
          - python2-pip
          - python2-devel
          - gcc
    - name: Install some libraries via PIP
      pip:
        executable: '/usr/bin/pip2'
        name: PyYAML, stompest, twisted, stompest.async, async
