---
- name: Install Python 2 + GCC + PIP + some Python libraries
  hosts: central_centreon
  gather_facts: false
  tasks:
    - name: Install Python 2 + GCC + PIP + some Python libraries
      dnf:
        name:
          - python2-pip
          - python2-devel
          - gcc
    - name: Install some libraries via PIP
      pip:
        executable: '/usr/bin/pip2'
        name: PyYAML==5.1.0, stompest.async==2.1.6, stompest==2.3.0, Twisted==12.2.0, async==0.6.2
