---
- name: Create users and needed directories
  hosts: central_centreon
  gather_facts: false
  tasks:
    - name: Create group grabinventorymonitoring
      group:
        name: grabinventorymonitoring
    - name: Create its directory
      file:
        path: /var/run/grabInventoryMonitoring
        owner: grabinventorymonitoring
        group: grabinventorymonitoring
      when: not ansible_check_mode  
    - name: Create user grabinventorymonitoring
      user:
        name: grabinventorymonitoring
        comment: Synchro Kace
        group: grabinventorymonitoring
        home: /var/run/grabInventoryMonitoring
